services:
  # PostgreSQL service
  analytics_api_postgres_prod:
    image: postgres:18
    container_name: analytics_api_postgres_prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - analytics_api_postgres_data_prod:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - analytics_api_prod_network

  # Django application service
  analytics_api_prod:
    container_name: analytics_api_prod
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - analytics_api_prod_network

volumes:
  analytics_api_postgres_data_prod:
  analytics_api_media_prod:

networks:
  analytics_api_prod_network:
    name: analytics_api_prod_network
